### ISSUE TITLE
Investigate connection leaks in trocla-hiera-backend

### ISSUE THREAD

**Issue by duritong** [duritong/puppet-trocla#25]
As reported on puppet-users, it seems that the hiera-backend is leaking stores:

https://groups.google.com/forum/#!topic/puppet-users/JDfXiA1xnCg

The workaround proposed on the list goes into the same direction as what we discussed in https://github.com/duritong/puppet-trocla/pull/18 and hence is introducing the same inefficiency (re-opening database connection), that I tried to avoid in the patches that followed to that PR.

Although, I explicitly tried to not run into the same problem as in the original puppet function with the hiera-backend, it looks like we are creating objects over and over again and hence keeping tons of connections open. Though that is my current guess and the little info we have on the report on the list, but it's the only explanation I have so far for the growing connection count.

What might interfere is the way how puppet is setting up the caches for hiera backends and eventually we might need to try to do that differently than storing the trocla object in the hash. But that's a pure guess atm, that needs more verification and analysis.

This is mainly a brain dump at the moment, to not loose track on what came up so far.

**Comment by Poil** [comment]
Hi,

On this node we have 2 call to trocla in the manifest
We also have a call via hiera
`
files:
  /tmp/toto:
    content: "%{hiera('trocla_lookup::plain::mykey')}"
`

At each run, a new connection is opened and not closed.
We have patched `lib/puppet/functions/trocla_lookup_key.rb `

`
diff --git a/lib/puppet/functions/trocla_lookup_key.rb b/lib/puppet/functions/trocla_lookup_key.rb
index d377ec8..f61df46 100644
--- a/lib/puppet/functions/trocla_lookup_key.rb
+++ b/lib/puppet/functions/trocla_lookup_key.rb
@@ -33,6 +33,8 @@ Puppet::Functions.create_function(:trocla_lookup_key) do
       trocla_hierarchy(trocla_key, format, opts)
     end
 
+    @trocla.close
+
     context.not_found unless res
     context.cache(key, res)
   end 
`

This seems to resolve this leak. We need to test more to see if there is no leak with the call in the manifests.

Best regards

**Comment by duritong** [comment]
Great, thank you a lot for the information.

So indicating that it is one connection per run and you have one hiera-trocla call, I think the remaining leak is there.

So now I'm wondering why the cache is not working as expected, but for that I need to dig further into how it works.

I'm glad to hear the patch you did works, though I don't see it as a long-term solution, as a) it works around the actual problem and b) it makes trocla inefficent on high usage, so I really would like to find the actual problem and a way to properly fix it.

2 remaining questions:

* How does your hiera config look like?
* Could I come up with a with debugging patches, that would help me understand what the problem could be and you could introduce them into your testing env? That would be great!

**Comment by Poil** [comment]
Hi,

If needed I can do more test and patch our test server :)

Here is our big hiera configuration
```
---
version: 5
defaults:
  datadir: '/etc/puppetlabs/code/hieradata'
  data_hash: yaml_data

hierarchy:
# FQDN (ex: custproj-pw01.adm.fr.clara.net)
  - name: Per fqdn data
    glob: hieradata-nodes-configuration/%{::kernel}/%{::client_code}/%{::project_code}/fqdn/%{::fqdn}/{classes,params,users,groups,files,packages,ssh_authorized_keys,exec,common}.yaml
# Client Cert (ex: custproj-pw01.adm.fr.clara.net)
  - name: Per clientcert data
    glob: hieradata-nodes-configuration/%{::kernel}/%{::client_code}/%{::project_code}/clientcert/%{::trusted.certname}/{classes,params,users,groups,files,packages,ssh_authorized_keys,exec,common}.yaml
# Role + SubRole + Platform (ex: webserver_prx_production)
  - name: Per role/subrole/platform
    glob: hieradata-nodes-configuration/%{::kernel}/%{::client_code}/%{::project_code}/claranet/%{::role}/%{::subrole}/%{::platform}/{classes,params,users,groups,files,packages,ssh_authorized_keys,exec,common}.yaml
# Role + Platform (ex: webserver_production)
  - name: Per role/platform
    glob: hieradata-nodes-configuration/%{::kernel}/%{::client_code}/%{::project_code}/claranet/%{::role}/all/%{::platform}/{classes,params,users,groups,files,packages,ssh_authorized_keys,exec,common}.yaml
# Subrole + Platform (ex: production)
  - name: Per subrole/platform
    glob: hieradata-nodes-configuration/%{::kernel}/%{::client_code}/%{::project_code}/claranet/all/%{::subrole}/%{::platform}/{classes,params,users,groups,files,packages,ssh_authorized_keys,exec,common}.yaml
# Platform (ex: production)
  - name: Per platform
    glob: hieradata-nodes-configuration/%{::kernel}/%{::client_code}/%{::project_code}/claranet/all/all/%{::platform}/{classes,params,users,groups,files,packages,ssh_authorized_keys,exec,common}.yaml
# Role + SubRole (ex: webserver_prx)
  - name: Per Role/Subrole
    glob: hieradata-nodes-configuration/%{::kernel}/%{::client_code}/%{::project_code}/claranet/%{::role}/%{::subrole}/all/{classes,params,users,groups,files,packages,ssh_authorized_keys,exec,common}.yaml
# Role (ex: webserver)
  - name: Per Role
    glob: hieradata-nodes-configuration/%{::kernel}/%{::client_code}/%{::project_code}/claranet/%{::role}/all/all/{classes,params,users,groups,files,packages,ssh_authorized_keys,exec,common}.yaml
# Domain
  - name: Per Domain
    glob: hieradata-nodes-configuration/%{::kernel}/%{::client_code}/%{::project_code}/other/%{::domain}/{classes,params,users,groups,files,packages,ssh_authorized_keys,exec,common}.yaml
# AWS AZ
  - name: Per AWS AZ
    glob: hieradata-nodes-configuration/%{::kernel}/%{::client_code}/%{::project_code}/other/%{::ec2_placement_availability_zone}/{classes,params,users,groups,files,packages,ssh_authorized_keys,exec,common}.yaml
# Project 
  - name: Per Project
    glob: hieradata-nodes-configuration/%{::kernel}/%{::client_code}/%{::project_code}/claranet/all/all/all/{classes,params,users,groups,files,packages,ssh_authorized_keys,exec,common}.yaml
# Client
  - name: Per Client
    glob: hieradata-nodes-configuration/%{::kernel}/%{::client_code}/all/{classes,params,users,groups,files,packages,ssh_authorized_keys,exec,common}.yaml
# Common
  - name: Per SOE/Location/AZ
    path: hieradata/%{::soe_version}/%{::location}/%{::ec2_placement_availability_zone}/common.yaml
  - name: Per SOE/Domain
    path: hieradata/%{::soe_version}/%{::domain}/common.yaml
  - name: Per SOE/Location
    path: hieradata/%{::soe_version}/%{::location}/common.yaml
  - name: Per SOE
    path: hieradata/%{::soe_version}/common.yaml
  - name: Per Location/AZ
    path: hieradata/%{::location}/%{::ec2_placement_availability_zone}/common.yaml
  - name: Per Location
    path: hieradata/%{::location}/common.yaml
  - name: Common
    path: hieradata/common.yaml
  - name: trocla
    lookup_key: trocla_lookup_key
    options:
      trocla_hierarchy:
        - defaults
      config: '/etc/puppetlabs/puppet/troclarc.yaml'
...
```
